### ISSUE TITLE
Failed to show database when calling exists()

### ISSUE THREAD

**Issue by saintus** [influxdata/influxdb-php#30] opened 2015-11-29 05:55 UTC
When calling exists() to check a DB, PHP will throw fatal error:

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Error creating resource: [message] fopen(http://127.0.0.1:8086/query?q=SHOW+DATABASES): failed to open stream: HTTP request failed!
[file] /project/lib/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 282' in /project/lib/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:222
Stack trace:
#0 /project/lib/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(286): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /project/lib/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /project/lib/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(42): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /project/lib/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware in /project/lib/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 51
---

I can manually use CURL or wget to successfully retrieve:
     http://127.0.0.1:8086/query?q=SHOW+DATABASES
but not from influxdb-php's exists(). 

It seems the error related with guzzle 6. 
Is there any one has similar issue like this?

**Comment by saintus** [comment] 2015-11-29 06:01
By the way, the installed InfluxDB is 0.9.5.1 on ubuntu 14.04.3.

**Comment by thecodeassassin** [comment] 2016-01-04 22:29
I used the following code to try to reproduce the bug:

```php
if ($database->exists()) {
   var_dump($database->getClient()->listDatabases());
}
```

but it just works. Can you paste some sample code that broke? I am using InfluxDB v0.9.6.1.

**Comment by thecodeassassin** [comment] 2016-01-05 15:36
@saintus  Closing this for now, please reply when you are still facing this issue.

**Closed by thecodeassassin** 2016-01-05 15:36 UTC

**Comment by yarikdot** [comment] 2016-02-16 15:47
I just hit this problem as well:

    use \InfluxDB\Client;
    use \InfluxDB\Database\RetentionPolicy;
    
    $client = new Client($host, $port);
    $database = $client->selectDb($db);
    
    if (!$database->exists()) {
        $database->create(new RetentionPolicy('test', '1d', 2, true));
    }

influxdb version:
root@server:~# dpkg -l | grep influx
ii  influxdb                       0.9.4.1                   amd64        Distributed time-series database
root@server:~#

composer.json: "influxdb/influxdb-php": "dev-master"

Installed today.

**Comment by yarikdot** [comment] 2016-02-16 16:01
Seems like a problem in guzzle. Fixed by installing php5-curl package.

**Comment by gianarb** [comment] 2016-02-16 16:02
Strange, only this request fails without php5-curl?

**Comment by thecodeassassin** [comment] 2016-02-16 22:50
@yarikdot shouldn't all requests fail without php5-curl? Anyways @gianarb maybe we should switch to using the php stream handler as default for all the requests?

**Comment by yarikdot** [comment] 2016-02-17 12:41
I have just tested writePoints and it fails as well.

@thecodeassassin I have feeling that guzzle has a fallback if php5-curl is not defined, it uses standard fopen on http. However, it can be blocked via allow_url_fopen (in my case it is enabled).

**Comment by gianarb** [comment] 2016-02-17 13:17
I think that it is more easy for us provide a default library without curl but with php-stream because it is ready to use.. but in my opinion our current constructor is not the best implementation `new GuzzleClient` into the `constructor` seems a bad practice.

I am thinking on a possibile new implementation but it is a BC break.. maybe if it will be good we can merge it for 2.0 release :) @thecodeassassin
